In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [15]:
data=pd.DataFrame({
    'x':[2.5,0.5,2.2,1.9,3.1,2.3,2,1,1.2,1.1],
    'y':[2.4,0.7,2.9,2.2,3.0,2.7,1.6,1.1,1.6,0.9]
})

In [16]:
data

x    y
0  2.5  2.4
1  0.5  0.7
2  2.2  2.9
3  1.9  2.2
4  3.1  3.0
5  2.3  2.7
6  2.0  1.6
7  1.0  1.1
8  1.2  1.6
9  1.1  0.9

In [17]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(data)
scaled_data=scaler.transform(data)
scaled_data

array([[ 0.944105  ,  0.61016865],
       [-1.67840889, -1.506743  ],
       [ 0.55072792,  1.23278973],
       [ 0.15735083,  0.36112022],
       [ 1.73085917,  1.35731394],
       [ 0.68185361,  0.9837413 ],
       [ 0.28847653, -0.38602507],
       [-1.02278042, -1.00864614],
       [-0.76052903, -0.38602507],
       [-0.89165472, -1.25769457]])

In [18]:
from sklearn.decomposition import PCA

In [19]:
pca=PCA(n_components=2)

In [20]:
pca.fit(scaled_data)

PCA(n_components=2)

In [21]:
x_pca=pca.transform(scaled_data)
x_pca

array([[-1.09903744, -0.23612866],
       [ 2.2522425 ,  0.12138612],
       [-1.26113742,  0.48229053],
       [-0.3666144 ,  0.14408672],
       [-2.18366814, -0.26413636],
       [-1.17775345,  0.21346683],
       [ 0.06897723, -0.47694465],
       [ 1.43643549,  0.00999444],
       [ 0.81073617,  0.26481429],
       [ 1.51981946, -0.25882926]])

In [29]:
#plt.figure(figsize=(10,4))
plt.scatter(x_pca[:,0],x_pca[:,1])
plt.xlabel('component 1')
plt.ylabel('component 2')

Text(0, 0.5, 'component 2')

In [25]:
pca.components_

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [26]:
d=pd.DataFrame(pca.components_,columns=['x','y'])
d

x         y
0 -0.707107 -0.707107
1 -0.707107  0.707107

In [28]:
import seaborn as sns
sns.heatmap(d,cmap='plasma')

<Axes: >