In [57]:
import numpy as np
from numpy.linalg import eigh, norm

In [58]:
# Define your input matrix A (3x3)

In [59]:
A = np.array([[2,0,0],
              [2,1,0],
              [0,-2,0]])

In [60]:
A

array([[ 2,  0,  0],
       [ 2,  1,  0],
       [ 0, -2,  0]])

In [61]:
# Step 1: Calculate A^T * A

In [62]:
ATA = A.T.dot(A)

In [63]:
ATA = A.T.dot(A)
ATA 

array([[8, 2, 0],
       [2, 5, 0],
       [0, 0, 0]])

In [64]:
# Step 2: Calculate the eigenvalues and eigenvectors of ATA using eigh


In [65]:
ATA = A.T.dot(A)
ATA 
eigenvalues_ATA, eigenvectors_ATA = eigh(ATA)

In [66]:
ATA = A.T.dot(A)
ATA 
eigenvalues_ATA, eigenvectors_ATA = eigh(ATA)
eigenvalues_ATA, eigenvectors_ATA

(array([0., 4., 9.]),
 array([[ 0.        ,  0.4472136 , -0.89442719],
        [ 0.        , -0.89442719, -0.4472136 ],
        [ 1.        ,  0.        , -0.        ]]))

In [67]:
# Step 3: Sort eigenvalues and eigenvectors in descending order

In [68]:
ATA = A.T.dot(A)
ATA 
eigenvalues_ATA, eigenvectors_ATA = eigh(ATA)
eigenvalues_ATA, eigenvectors_ATA
sorted_indices = np.argsort(eigenvalues_ATA)[::-1]
eigenvalues_ATA = eigenvalues_ATA[sorted_indices]
eigenvectors_ATA = eigenvectors_ATA[:, sorted_indices]

In [69]:
# Step 4: Calculate singular values from the square root of eigenvalues

In [70]:
ATA = A.T.dot(A)
ATA 
eigenvalues_ATA, eigenvectors_ATA = eigh(ATA)
eigenvalues_ATA, eigenvectors_ATA
sorted_indices = np.argsort(eigenvalues_ATA)[::-1]
eigenvalues_ATA = eigenvalues_ATA[sorted_indices]
eigenvectors_ATA = eigenvectors_ATA[:, sorted_indices]
singular_values = np.sqrt(eigenvalues_ATA)

In [71]:
ATA = A.T.dot(A)
ATA 
eigenvalues_ATA, eigenvectors_ATA = eigh(ATA)
eigenvalues_ATA, eigenvectors_ATA
sorted_indices = np.argsort(eigenvalues_ATA)[::-1]
eigenvalues_ATA = eigenvalues_ATA[sorted_indices]
eigenvectors_ATA = eigenvectors_ATA[:, sorted_indices]
singular_values = np.sqrt(eigenvalues_ATA)
singular_values

array([3., 2., 0.])

In [72]:
# Step 5: Create the diagonal matrix S (3x3)

In [73]:
ATA = A.T.dot(A)
ATA 
eigenvalues_ATA, eigenvectors_ATA = eigh(ATA)
eigenvalues_ATA, eigenvectors_ATA
sorted_indices = np.argsort(eigenvalues_ATA)[::-1]
eigenvalues_ATA = eigenvalues_ATA[sorted_indices]
eigenvectors_ATA = eigenvectors_ATA[:, sorted_indices]
singular_values = np.sqrt(eigenvalues_ATA)
singular_values
S = np.zeros_like(A, dtype=float)
S[:A.shape[0], :A.shape[1]] = np.diag(singular_values)

In [74]:
ATA = A.T.dot(A)
ATA 
eigenvalues_ATA, eigenvectors_ATA = eigh(ATA)
eigenvalues_ATA, eigenvectors_ATA
sorted_indices = np.argsort(eigenvalues_ATA)[::-1]
eigenvalues_ATA = eigenvalues_ATA[sorted_indices]
eigenvectors_ATA = eigenvectors_ATA[:, sorted_indices]
singular_values = np.sqrt(eigenvalues_ATA)
singular_values
S = np.zeros_like(A, dtype=float)
S[:A.shape[0], :A.shape[1]] = np.diag(singular_values)
S[:A.shape[0], :A.shape[1]]

array([[3., 0., 0.],
       [0., 2., 0.],
       [0., 0., 0.]])

In [75]:
# Step 6: Calculate U from A and the eigenvectors of ATA

In [76]:
ATA = A.T.dot(A)
ATA 
eigenvalues_ATA, eigenvectors_ATA = eigh(ATA)
eigenvalues_ATA, eigenvectors_ATA
sorted_indices = np.argsort(eigenvalues_ATA)[::-1]
eigenvalues_ATA = eigenvalues_ATA[sorted_indices]
eigenvectors_ATA = eigenvectors_ATA[:, sorted_indices]
singular_values = np.sqrt(eigenvalues_ATA)
singular_values
S = np.zeros_like(A, dtype=float)
S[:A.shape[0], :A.shape[1]] = np.diag(singular_values)
S[:A.shape[0], :A.shape[1]]
U = A.dot(eigenvectors_ATA)

In [77]:
# Normalize U to make it an orthonormal matrix


In [78]:
ATA = A.T.dot(A)
ATA 
eigenvalues_ATA, eigenvectors_ATA = eigh(ATA)
eigenvalues_ATA, eigenvectors_ATA
sorted_indices = np.argsort(eigenvalues_ATA)[::-1]
eigenvalues_ATA = eigenvalues_ATA[sorted_indices]
eigenvectors_ATA = eigenvectors_ATA[:, sorted_indices]
singular_values = np.sqrt(eigenvalues_ATA)
singular_values
S = np.zeros_like(A, dtype=float)
S[:A.shape[0], :A.shape[1]] = np.diag(singular_values)
S[:A.shape[0], :A.shape[1]]
U = A.dot(eigenvectors_ATA)
U /= norm(U, axis=0)

C:\Users\avinash\AppData\Local\Temp\ipykernel_1816\4239885122.py:1: RuntimeWarning: invalid value encountered in divide
  U /= norm(U, axis=0)


In [79]:
# Step 7: Calculate Vt (transpose of V) from the eigenvectors of ATA

In [80]:
ATA = A.T.dot(A)
ATA 
eigenvalues_ATA, eigenvectors_ATA = eigh(ATA)
eigenvalues_ATA, eigenvectors_ATA
sorted_indices = np.argsort(eigenvalues_ATA)[::-1]
eigenvalues_ATA = eigenvalues_ATA[sorted_indices]
eigenvectors_ATA = eigenvectors_ATA[:, sorted_indices]
singular_values = np.sqrt(eigenvalues_ATA)
singular_values
S = np.zeros_like(A, dtype=float)
S[:A.shape[0], :A.shape[1]] = np.diag(singular_values)
S[:A.shape[0], :A.shape[1]]
U = A.dot(eigenvectors_ATA)
U /= norm(U, axis=0)
Vt = eigenvectors_ATA.T



In [81]:
# Print the matrices U, S, and Vt


In [83]:
ATA = A.T.dot(A)
ATA 
eigenvalues_ATA, eigenvectors_ATA = eigh(ATA)
eigenvalues_ATA, eigenvectors_ATA
sorted_indices = np.argsort(eigenvalues_ATA)[::-1]
eigenvalues_ATA = eigenvalues_ATA[sorted_indices]
eigenvectors_ATA = eigenvectors_ATA[:, sorted_indices]
singular_values = np.sqrt(eigenvalues_ATA)
singular_values
S = np.zeros_like(A, dtype=float)
S[:A.shape[0], :A.shape[1]] = np.diag(singular_values)
S[:A.shape[0], :A.shape[1]]
U = A.dot(eigenvectors_ATA)
U /= norm(U, axis=0)
Vt = eigenvectors_ATA.T


print("Matrix U (3x3):")
print(U)
print("\nMatrix S (3x3):")
print(S)
print("\nMatrix Vt (3x3):")
print(Vt)

Matrix U (3x3):
[[-0.59628479  0.4472136          nan]
 [-0.74535599  0.                 nan]
 [ 0.2981424   0.89442719         nan]]

Matrix S (3x3):
[[3. 0. 0.]
 [0. 2. 0.]
 [0. 0. 0.]]

Matrix Vt (3x3):
[[-0.89442719 -0.4472136  -0.        ]
 [ 0.4472136  -0.89442719  0.        ]
 [ 0.          0.          1.        ]]


C:\Users\avinash\AppData\Local\Temp\ipykernel_1816\3138158194.py:14: RuntimeWarning: invalid value encountered in divide
  U /= norm(U, axis=0)
