In [2]:
import numpy as np
from numpy.linalg import norm,eigh

In [9]:
A=np.array([[2,0,0],
    [2,1,0],
    [0,-2,0]])
print(A)

[[ 2  0  0]
 [ 2  1  0]
 [ 0 -2  0]]


In [11]:
ATA=A.T.dot(A)
ATA

array([[8, 2, 0],
       [2, 5, 0],
       [0, 0, 0]])

In [12]:
eighvalues_ATA,eighvectors_ATA=eigh(ATA)
eighvalues_ATA,eighvectors_ATA

(array([0., 4., 9.]),
 array([[ 0.        ,  0.4472136 , -0.89442719],
        [ 0.        , -0.89442719, -0.4472136 ],
        [ 1.        ,  0.        , -0.        ]]))

In [13]:
sorted_indices=np.argsort(eighvalues_ATA)[::-1]
eighvalues_ATA=eighvalues_ATA[sorted_indices]
eighvectors_ATA=eighvectors_ATA[:,sorted_indices]

In [14]:
eighvalues_ATA,eighvectors_ATA

(array([9., 4., 0.]),
 array([[-0.89442719,  0.4472136 ,  0.        ],
        [-0.4472136 , -0.89442719,  0.        ],
        [-0.        ,  0.        ,  1.        ]]))

In [15]:
singular_values=np.sqrt(eighvalues_ATA)
singular_values

array([3., 2., 0.])

In [17]:
s=np.zeros_like(A,dtype=float)
s[:A.shape[0],:A.shape[1]]=np.diag(singular_values)

In [18]:
s[:A.shape[0],:A.shape[1]]

array([[3., 0., 0.],
       [0., 2., 0.],
       [0., 0., 0.]])

In [26]:
u=A.dot(eighvectors_ATA)
u/=norm(u,axis=0)
vt=eighvectors_ATA.T

C:\Users\avinash\AppData\Local\Temp\ipykernel_1932\3705263765.py:2: RuntimeWarning: invalid value encountered in divide
  u/=norm(u,axis=0)


In [23]:
s

array([[3., 0., 0.],
       [0., 2., 0.],
       [0., 0., 0.]])

In [27]:
vt

array([[-0.89442719, -0.4472136 , -0.        ],
       [ 0.4472136 , -0.89442719,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [25]:
u

array([[-0.59628479,  0.4472136 ,         nan],
       [-0.74535599,  0.        ,         nan],
       [ 0.2981424 ,  0.89442719,         nan]])